apiVersion: apps/v1
kind: Deployment
metadata:
  name: noise-generator
  namespace: medical-data
spec:
  replicas: 2
  selector:
    matchLabels:
      app: noise-generator # Phải khớp với label ở dưới
  template:
    metadata:
      labels:
        app: noise-generator # Selector tìm Pod dựa vào nhãn này
    spec:
      containers:
      - name: noise
        image: traffic-simulator:v1
        imagePullPolicy: Never # Vì ta đã 'kind load' image local
        command: ["python", "noise_gen.py"]
        env:
        - name: TARGET_URL
          # Dùng DNS nội bộ của K8s để gọi App
          value: "http://target-app-service.medical-data.svc.cluster.local/health-check"